name: Build DEB Package

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip python3-setuptools dpkg-dev debhelper fakeroot
        sudo apt-get install -y python3-pyqt5 python3-pil python3-xlib imagemagick
        sudo apt-get install -y python3-wheel python3-tk
        pip3 install pyinstaller pynput pillow pyperclip
    
    - name: Build DEB package
      run: |
        chmod +x build_kylin_package.sh
        sudo ./build_kylin_package.sh
        ls -la *.deb || echo "No deb file found"
        pwd
    
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: screenshot-ftp-uploader-deb
        path: screenshot-ftp-uploader_kylin-v10_amd64.deb
        if-no-files-found: error 